server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://diff.c78k86o8iw7w.ap-northeast-2.rds.amazonaws.com:3306/project_Y?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: admin
    password: teamprojecty


  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 
            client-secret:
            scope: user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub

          google:
            client-id:
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - profile
              - email
            client-name: Google
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

mybatis:
  type-aliases-package: org.example.vo
  mapper-locations: classpath:/mappers/**/*.xml

logging:
  level:
    org.mybatis: DEBUG
    org.example.repository: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core.endpoint: DEBUG

sonarqube:
  host: http://localhost:9000
  token: sqa_51b039c183b6985ee4486ab5195fd964fb4d92ba
